### ISSUE TITLE
Missing import for Monoid

### ISSUE THREAD

**Issue by MarcelH91** [softlang/yas#1]
When I try to open BIPL implementation's Main.hs file in ghci I get the following error concerned with a missing import at Data\Perhaps\Utilities :

![missingimport](https://cloud.githubusercontent.com/assets/8490924/16098427/28b1c1f0-3353-11e6-93bb-a0b7b39eafc1.jpg)

After adding `import Data.Monoid (Monoid,mappend,mempty)' I get another error message concerned with a missing import at Language.BIPL.SIGN.V2.Analysis.
![missingimport2](https://cloud.githubusercontent.com/assets/8490924/16098530/d04a6782-3353-11e6-8f79-3fb90def0b2f.jpg)

This is fixed by adding `import Data.Monoid (mconcat)'

GHCi version : The Glorious Glasgow Haskell Compilation System, version 7.8.3

**Comment by rlaemmel** [comment]
Doesn't seem to be an issue with 7.10.
However, you fix also works with 7.10.
